# Generated by Django 6.0 on 2026-04-09 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleAuth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_user_id",
                    models.CharField(
                        help_text="Opaque user ID from the calling application",
                        max_length=255,
                    ),
                ),
                (
                    "_access_token",
                    models.TextField(
                        db_column="access_token", help_text="Encrypted access token"
                    ),
                ),
                (
                    "_refresh_token",
                    models.TextField(
                        blank=True,
                        db_column="refresh_token",
                        help_text="Encrypted refresh token",
                        null=True,
                    ),
                ),
                ("token_type", models.CharField(default="bearer", max_length=50)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("account_id", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("display_name", models.CharField(blank=True, max_length=255)),
                ("scopes", models.JSONField(blank=True, default=list)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("google_user_id", models.CharField(blank=True, max_length=100)),
                (
                    "app_client",
                    models.ForeignKey(
                        help_text="The application that owns this connection",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_connections",
                        to="core.appclient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Google Authentication",
                "verbose_name_plural": "Google Authentications",
                "db_table": "nemi_storage_google_auth",
                "indexes": [
                    models.Index(
                        fields=["app_client", "is_active"],
                        name="stggl_client_active_idx",
                    ),
                    models.Index(fields=["expires_at"], name="stggl_expires_idx"),
                    models.Index(fields=["email"], name="stggl_email_idx"),
                ],
                "unique_together": {("app_client", "external_user_id")},
            },
        ),
    ]
