# Generated by Django 6.0 on 2026-04-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='App name, e.g. "nai-backend", "indoxhub"',
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "api_key_hash",
                    models.CharField(
                        editable=False,
                        help_text="SHA-256 hash of the API key",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "api_key_prefix",
                    models.CharField(
                        editable=False,
                        help_text="First 8 chars for identification",
                        max_length=8,
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of scopes: ["social", "storage", "notify"]',
                    ),
                ),
                ("rate_limit_per_minute", models.PositiveIntegerField(default=60)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "nemi_app_client",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["api_key_prefix"], name="nemi_app_cl_api_key_6e411e_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="nemi_app_cl_is_acti_505618_idx"
                    ),
                ],
            },
        ),
    ]
