# Generated by Django 6.0 on 2026-04-09 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly name, e.g., 'Marketing Slack', 'Admin Telegram'",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("slack", "Slack"),
                            ("discord", "Discord"),
                            ("telegram", "Telegram"),
                            ("msteams", "Microsoft Teams"),
                            ("matrix", "Matrix"),
                            ("mattermost", "Mattermost"),
                            ("rocketchat", "Rocket.Chat"),
                            ("zulip", "Zulip"),
                            ("googlechat", "Google Chat"),
                            ("flock", "Flock"),
                            ("guilded", "Guilded"),
                            ("revolt", "Revolt"),
                            ("feishu", "Feishu"),
                            ("synology", "Synology Chat"),
                            ("wecombot", "WeCom Bot"),
                            ("webex", "Webex Teams"),
                            ("twist", "Twist"),
                            ("ryver", "Ryver"),
                            ("pushover", "Pushover"),
                            ("gotify", "Gotify"),
                            ("ntfy", "ntfy"),
                            ("pushbullet", "Pushbullet"),
                            ("join", "Join"),
                            ("simplepush", "Simplepush"),
                            ("pushsafer", "Pushsafer"),
                            ("pushy", "Pushy"),
                            ("bark", "Bark"),
                            ("pushdeer", "PushDeer"),
                            ("techulus", "Techulus Push"),
                            ("notica", "Notica"),
                            ("chanify", "Chanify"),
                            ("pushme", "PushMe"),
                            ("prowl", "Prowl"),
                            ("email", "Email (SMTP)"),
                            ("ses", "AWS SES"),
                            ("sendgrid", "SendGrid"),
                            ("mailgun", "Mailgun"),
                            ("sparkpost", "SparkPost"),
                            ("smtp2go", "SMTP2Go"),
                            ("resend", "Resend"),
                            ("office365", "Office 365"),
                            ("brevo", "Brevo"),
                            ("sendpulse", "SendPulse"),
                            ("twilio", "Twilio SMS"),
                            ("vonage", "Vonage (Nexmo)"),
                            ("messagebird", "MessageBird"),
                            ("clickatell", "Clickatell"),
                            ("sns", "AWS SNS"),
                            ("plivo", "Plivo"),
                            ("d7networks", "D7 Networks"),
                            ("bulksms", "BulkSMS"),
                            ("clicksend", "ClickSend"),
                            ("sinch", "Sinch"),
                            ("seven", "Seven"),
                            ("msg91", "MSG91"),
                            ("bulkvs", "BulkVS"),
                            ("burstsms", "Burst SMS"),
                            ("httpsms", "httpSMS"),
                            ("pagerduty", "PagerDuty"),
                            ("opsgenie", "Opsgenie"),
                            ("splunk", "Splunk On-Call"),
                            ("signl4", "SIGNL4"),
                            ("pagertree", "PagerTree"),
                            ("notifiarr", "Notifiarr"),
                            ("jira", "Jira"),
                            ("rsyslog", "RSyslog"),
                            ("twitter", "X (Twitter)"),
                            ("mastodon", "Mastodon"),
                            ("reddit", "Reddit"),
                            ("bluesky", "BlueSky"),
                            ("whatsapp", "WhatsApp"),
                            ("line", "LINE"),
                            ("json", "Webhook (JSON)"),
                            ("xml", "Webhook (XML)"),
                            ("form", "Webhook (Form)"),
                            ("homeassistant", "Home Assistant"),
                            ("ifttt", "IFTTT"),
                            ("kodi", "KODI"),
                            ("lametric", "LaMetric Time"),
                            ("apprise_api", "Apprise API"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict,
                        help_text="Service-specific configuration (tokens, webhooks, etc.)",
                    ),
                ),
                (
                    "apprise_url",
                    models.TextField(
                        blank=True,
                        editable=False,
                        help_text="Auto-generated Apprise URL from config",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_channels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("alert", "Alert"),
                            ("digest", "Digest"),
                            ("health", "Health Check"),
                            ("custom", "Custom"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "title_template",
                    models.CharField(
                        help_text="Supports variables: {app_name}, {count}, etc.",
                        max_length=250,
                    ),
                ),
                (
                    "body_template",
                    models.TextField(
                        help_text="Supports variables: {app_name}, {count}, etc."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channels",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Channels to send this notification to",
                        related_name="templates",
                        to="notify.notificationchannel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        blank=True,
                        help_text="Notification source (e.g. social, storage, health)",
                        max_length=50,
                    ),
                ),
                (
                    "source_id",
                    models.IntegerField(
                        blank=True, help_text="ID of the source object", null=True
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("context_data", models.JSONField(blank=True, default=dict)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "channel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="notify.notificationchannel",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="notify.notificationtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="notificationchannel",
            index=models.Index(
                fields=["is_active"], name="notify_noti_is_acti_420005_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationchannel",
            index=models.Index(
                fields=["service_type"], name="notify_noti_service_895dec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(fields=["status"], name="notify_noti_status_177b43_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["channel", "created_at"], name="notify_noti_channel_4dcc87_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["source_type", "source_id"],
                name="notify_noti_source__76ad16_idx",
            ),
        ),
    ]
