# Generated by Django 5.2.13 on 2026-04-09 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_user_id", models.CharField(max_length=255)),
                ("platform", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("media_url", models.URLField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("error", models.TextField(blank=True, null=True)),
                ("external_id", models.CharField(blank=True, max_length=255)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "app_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_post_logs",
                        to="core.appclient",
                    ),
                ),
            ],
            options={
                "db_table": "nemi_post_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["app_client", "external_user_id", "platform"],
                        name="nemi_post_l_app_cli_a70035_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="nemi_post_l_status_b122b2_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SocialAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_user_id",
                    models.CharField(
                        help_text="Opaque user ID from the calling application",
                        max_length=255,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        help_text="Platform name (telegram, discord, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "_credentials",
                    models.TextField(
                        db_column="credentials",
                        help_text="Fernet-encrypted JSON credentials",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "health_status",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("healthy", "Healthy"),
                            ("unhealthy", "Unhealthy"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                ("last_health_check", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "app_client",
                    models.ForeignKey(
                        help_text="The application that owns this account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts",
                        to="core.appclient",
                    ),
                ),
            ],
            options={
                "db_table": "nemi_social_account",
                "indexes": [
                    models.Index(
                        fields=["app_client", "external_user_id", "platform"],
                        name="nemi_social_app_cli_49d91f_idx",
                    )
                ],
                "unique_together": {("app_client", "external_user_id", "platform")},
            },
        ),
    ]
